{
 "title": "Replicator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Replication progress, %",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processed_position{app=\"replicator\"} / last_known_position{app=\"replicator\"} * 100",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Source last position",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_known_position{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Source read position",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "read_position{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Source processed position",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processed_position{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Event read",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_reads_count{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Event written",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_writes_count{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Sink position",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sink_position{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Replication gap, position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "events" }
   ],
   "targets": [
    {
     "expr": "last_known_position{app=\"replicator\"}-processed_position{app=\"replicator\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Event writes, per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_writes_count{app=\"replicator\"}[2m])) by (environment)",
     "legendFormat": "{{environment}}"
    }
   ]
  }
 ]
}