apiVersion: v1
data:
  transform.js: |-
{{ .Values.transformJs | indent 4 }}

kind: ConfigMap
metadata:
  name: {{ template "replicator.fullname" . }}-transform-js
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
