prometheus:
  metrics: false
  operator: false
pvc:
  storageClass: null
terminationGracePeriodSeconds: 300
jsConfigMaps: []
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
image:
  registry: docker.io
  repository: eventstore/replicator
  tag: 0.4.6
  pullPolicy: IfNotPresent
replicator:
  reader:
    connectionString:
    protocol: tcp
  sink:
    connectionString:
    protocol: grpc
    partitionCount: 1
    partitioner:
    bufferSize: 1000
  scavenge: true
  filters: []
  transform: null
  checkpoint:
    type: file
    path: ./checkpoint
    checkpointAfter: 1000
transformJs: |-

#  restartOnFailure: false
#  runContinuously: true
