name: Replicator / Publish Helm Chart
on:
  push:
    paths:
      - 'charts/**'
    branches:
      - master

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Helm
        uses: azure/setup-helm@v4
      - 
        name: Publish Helm Chart
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"