name: Update Changelog
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Every day at 3am UTC.
jobs:
  updateChangelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Update changelog for Replicator
        uses: EventStore/Automations/changelog-update@master
        with:
          github-token: ${{ secrets.ORG_GH_BOT_AUTOMATION }}
          mode: batch
